apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost-redis
  namespace: collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost-redis
  template:
    metadata:
      labels:
        app: docmost-redis
    spec:
      containers:
      - name: redis
        image: bitnamilegacy/redis:7.4.1-debian-12-r2
        env:
        - name: REDIS_PASSWORD
          value: "abc123"
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis/data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: docmost-redis
  namespace: collaboration
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: docmost-redis
