apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: titan-system
  description: Titan Microservices System
spec:
  owner: guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: export-batch-service
  description: Export Batch Service for Titan
  annotations:
    backstage.io/kubernetes-label-selector: "app=export-batch-service"
    backstage.io/kubernetes-id: "export-batch-service"
spec:
  type: service
  lifecycle: production
  owner: guest
  system: titan-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ledger-service
  description: Ledger Service for Titan
  annotations:
    backstage.io/kubernetes-label-selector: "app=ledger-service"
    backstage.io/kubernetes-id: "ledger-service"
spec:
  type: service
  lifecycle: production
  owner: guest
  system: titan-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mock-regulatory-service
  description: Mock Regulatory Service for Titan
  annotations:
    backstage.io/kubernetes-label-selector: "app=mock-regulatory-service"
    backstage.io/kubernetes-id: "mock-regulatory-service"
spec:
  type: service
  lifecycle: production
  owner: guest
  system: titan-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Payment Service for Titan
  annotations:
    backstage.io/kubernetes-label-selector: "app=payment-service"
    backstage.io/kubernetes-id: "payment-service"
spec:
  type: service
  lifecycle: production
  owner: guest
  system: titan-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wallet-service
  description: Wallet Service for Titan
  annotations:
    backstage.io/kubernetes-label-selector: "app=wallet-service"
    backstage.io/kubernetes-id: "wallet-service"
spec:
  type: service
  lifecycle: production
  owner: guest
  system: titan-system
