cluster:
  nodes: 6
  replicas: 1

usePassword: true
existingSecret: "redis-cluster-credentials"
existingSecretPasswordKey: "redis-password"

service:
  type: LoadBalancer
  loadBalancerIP: "10.0.0.202"

persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  size: 5Gi

redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
