- logo:
    icon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png
- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: long
- kubernetes:
    cluster: homelab-cluster
    nodes: true
- resources:
    cpu: true
    memory: true
    disk: /
