apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: nexus-auth
  namespace: nexus
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: titan-app-role
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nexus-db-cluster-app
  namespace: nexus
spec:
  vaultAuthRef: nexus-auth
  mount: secret
  type: kv-v2
  path: titan/nexus-db-cluster-app
  destination:
    name: nexus-db-cluster-app
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: nexus
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nexus-admin-credentials
  namespace: nexus
spec:
  vaultAuthRef: nexus-auth
  mount: secret
  type: kv-v2
  path: titan/nexus-admin-credentials
  destination:
    name: nexus-admin-credentials
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nexus-deployer-credentials
  namespace: nexus
spec:
  vaultAuthRef: nexus-auth
  mount: secret
  type: kv-v2
  path: titan/nexus-deployer-credentials
  destination:
    name: nexus-deployer-credentials
    create: true
    overwrite: true
