apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 31.0.0
    chart: kafka
    helm:
      values: |
        image:
          repository: bitnamilegacy/kafka
          tag: 3.9.0-debian-12-r0
        
        kraft:
          enabled: true
        zookeeper:
          enabled: false

        externalAccess:
          enabled: true
          service:
            type: LoadBalancer
            port: 9094
          domain: homelab
        
        listeners:
          client:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
        auth:
          clientProtocol: plaintext
          interBrokerProtocol: plaintext

        controller:
          replicaCount: 1
          persistence:
            enabled: true
            storageClass: "openebs-hostpath"
            size: 5Gi

        broker:
          replicaCount: 3
          extraConfig: |-
            log.retention.hours=-1
            log.retention.bytes=-1
          persistence:
            enabled: true
            storageClass: "openebs-hostpath"
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi

        metrics:
          jmx:
            enabled: true
            image:
              repository: bitnamilegacy/jmx-exporter
              tag: 1.0.1-debian-12-r9
          kafka:
            enabled: true
          serviceMonitor:
            enabled: true
            interval: 30s
            scrapeTimeout: 30s
            labels:
              release: kube-prometheus-stack

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true