apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-client
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/oauth2-proxy-client
  destination:
    name: oauth2-proxy-client
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: oauth2-proxy
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-cookie-secret
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/oauth2-proxy-cookie
  destination:
    name: oauth2-proxy-cookie
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: oauth2-proxy
