apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: istio-system
spec:
  secretName: wildcard-cert
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "homelab"
    - "argocd.homelab"
    - "authorization.homelab"
    - "chaos.homelab"
    - "export-batch.homelab"
    - "fee.homelab"
    - "fraud.homelab"
    - "fx.homelab"
    - "grafana.homelab"
    - "homepage.homelab"
    - "kiali.homelab"
    - "ledger.homelab"
    - "limits.homelab"
    - "localstack.homelab"
    - "outbox-relay.homelab"
    - "payment.homelab"
    - "registry.homelab"
    - "registry-ui.homelab"
    - "regulatory.homelab"
    - "sanctions.homelab"
    - "vault.homelab"
    - "wallet.homelab"
    - "webhooks.homelab"
    - "workflows.homelab"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-cert
    hosts:
    - "*"
