apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: keycloak-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "https://keycloak.homelab/realms/master"
      jwksUri: "http://titan-keycloak-service.security.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"
    - issuer: "https://keycloak.homelab/realms/titan"
      jwksUri: "http://titan-keycloak-service.security.svc.cluster.local:8080/realms/titan/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-keycloak-jwt-payment
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    # USER: any valid token issued by the titan realm, no role required
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            hosts: ["payment.homelab"]
      when:
        - key: request.auth.claims[iss]
          values: ["https://keycloak.homelab/realms/titan"]
    # ADMIN: valid token from master realm, must carry the admin role in its groups claim
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            hosts: ["payment.homelab"]
      when:
        - key: request.auth.claims[iss]
          values: ["https://keycloak.homelab/realms/master"]
        - key: request.auth.claims[groups]
          values: ["admin"]
