apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: kafka-external-clients
  namespace: security
spec:
  realmRef:
    name: titan
    kind: KeycloakRealm
  clientId: kafka-external-clients
  public: false
  secret: $keycloak-kafka-external-clients:client-secret
  directAccess: false
  standardFlowEnabled: false
  serviceAccount:
    enabled: true
