apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: titan-keycloak
  namespace: security
spec:
  secret: keycloak-admin-credentials
  url: http://titan-keycloak-service.security.svc.cluster.local:8080
