apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: titan-test-user
  namespace: security
spec:
  realmRef:
    name: titan
    kind: KeycloakRealm
  username: test-user
  enabled: true
  email: test-user@homelab
  emailVerified: true
  firstName: Test
  lastName: User
  keepResource: true
  passwordSecret:
    name: titan-test-user
    key: password
