apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: titan-test-user
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/titan-test-user
  destination:
    name: titan-test-user
    create: true
