{{- range $appKey, $app := .Values.apps }}
{{- if $app.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $app.ingress.name | default (print $appKey $app.ingress._name_suffix) }}
  namespace: applications
  annotations:
  {{- if eq $app.ingress.ingressType "grpc" }}
{{ toYaml $.Values.global.ingressAnnotations | indent 4 }}
  {{- else if eq $app.ingress.ingressType "http" }}
{{ toYaml $.Values.global.ingressAnnotationsHttp | indent 4 }}
  {{- end }}
  {{- if $app.ingress.annotations }}
{{ toYaml $app.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if $app.ingress.tls }}
  tls:
{{ toYaml $app.ingress.tls | indent 4 }}
  {{- end }}
  rules:
{{ toYaml $app.ingress.rules | indent 2 }}
{{- end }}
{{- end }}
