{{- range $appKey, $app := .Values.apps }}
{{- if $app.ingress }}
{{- $baseName := trimPrefix "mock-" (trimSuffix "-service" $appKey) }}
{{- $hostName := printf "%s.homelab" $baseName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appKey }}-ingress
  namespace: applications
  annotations:
  {{- if eq $app.ingress.ingressType "grpc" }}
{{ toYaml $.Values.global.ingressAnnotations | indent 4 }}
  {{- else if eq $app.ingress.ingressType "http" }}
{{ toYaml $.Values.global.ingressAnnotationsHttp | indent 4 }}
  {{- end }}
  {{- if $app.ingress.annotations }}
{{ toYaml $app.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ $hostName }}
    secretName: {{ $baseName }}-tls-secret
  rules:
  - host: {{ $hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $appKey }}
            port:
              number: {{ $app.ingress.port }}
{{- end }}
{{- end }}
