apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: titan-auth
  namespace: applications
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: titan-app-role
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payment-db-secret
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/payment-db-cluster-app
  destination:
    name: payment-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: export-db-secret
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/export-db-cluster-app
  destination:
    name: export-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wallet-db-secret
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/wallet-db-cluster-app
  destination:
    name: wallet-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: limits-db-secret
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/limits-db-cluster-app
  destination:
    name: limits-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ledger-db-secret
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/ledger-db-cluster-app
  destination:
    name: ledger-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-cluster-credentials
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/redis-cluster-credentials
  destination:
    name: redis-cluster-credentials
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-payment-service-client
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/keycloak-payment-service-client
  destination:
    name: keycloak-payment-service-client
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: titan-test-user
  namespace: applications
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/titan-test-user
  destination:
    name: titan-test-user
    create: true
