{
 "title": "Job Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "The real-time velocity of your batch chunking.",
   "type": "timeseries",
   "description": "This tracks how fast your  KafkaItemReader  is gobbling up items.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (spring_batch_item_read_step_name) (rate(spring_batch_item_read_seconds_count[1m]))",
     "legendFormat": "{{spring_batch_item_read_step_name}}"
    }
   ]
  },
  {
   "title": "Step Duration Breakdown",
   "type": "timeseries",
   "description": "Since your job has multiple steps (e.g.,  managerStep  and partitioned  workerStep s), you can graph which step is the bottleneck",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (spring_batch_step_name) (rate(spring_batch_step_seconds_sum[5m])) / sum by (spring_batch_step_name) (rate(spring_batch_step_seconds_count[5m]))",
     "legendFormat": "{{spring_batch_step_name}}"
    }
   ]
  },
  {
   "title": "Live Running Jobs",
   "type": "timeseries",
   "description": "This tracks exactly how many jobs are actively executing right now in the background. ",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (spring_batch_job_name) (round(increase(spring_batch_job_seconds_count[1m])))",
     "legendFormat": "{{spring_batch_job_name}}"
    }
   ]
  },
  {
   "title": "Live Running Steps",
   "type": "timeseries",
   "description": "This tracks how many steps are actively executing.",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (spring_batch_step_name) (round(increase(spring_batch_step_seconds_count[1m])))",
     "legendFormat": "{{spring_batch_step_name}}"
    }
   ]
  },
  {
   "title": "Job Duration Trend",
   "type": "timeseries",
   "description": " Instead of just seeing a static duration, you can graph the average duration of your batch jobs over time to detect if they are gradually getting slower. ",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (spring_batch_job_name) (rate(spring_batch_job_seconds_sum[5m])) / sum by (spring_batch_job_name) (rate(spring_batch_job_seconds_count[5m]))",
     "legendFormat": "{{spring_batch_job_name}}"
    }
   ]
  },
  {
   "title": "Jobs Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (spring_batch_job_name) (spring_batch_job_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}