apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db-cluster
  namespace: databases
spec:
  instances: 2
  certificates:
    serverCASecret: homelab-ca-bundle
    serverTLSSecret: keycloak-db-cluster-server-tls
  monitoring:
    enablePodMonitor: true
  storage:
    size: 10Gi
    storageClass: "openebs-hostpath"
  bootstrap:
    initdb:
      database: keycloak
      owner: app
