apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ledger-db-cluster
  namespace: databases
spec:
  instances: 3
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: ledger-db-cluster-rw-lb
            spec:
              type: LoadBalancer
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432
  storage:
    size: 20Gi
    storageClass: "openebs-hostpath"
  bootstrap:
    initdb:
      database: ledger_db
      owner: app
