apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallet-db-cluster
  namespace: databases
spec:
  instances: 2
  certificates:
    serverCASecret: homelab-ca-bundle
    serverTLSSecret: wallet-db-cluster-server-tls
  postgresql:
    pg_hba:
      - hostssl all all all scram-sha-256
      - host all all all reject
  monitoring:
    enablePodMonitor: true
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: wallet-db-cluster-rw-lb
            spec:
              type: LoadBalancer
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432
  storage:
    size: 10Gi
    storageClass: "longhorn"
  bootstrap:
    initdb:
      database: wallet_db
      owner: app
