apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: container-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"

        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: container-registry
spec:
  type: ClusterIP
  clusterIP: 10.96.100.1
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: docker-registry
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: docker-registry
  namespace: container-registry
spec:
  hosts:
  - "registry.homelab"
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: docker-registry
        port:
          number: 80
    corsPolicy:
      allowOrigins:
      - exact: https://registry-ui.homelab
      allowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
      allowHeaders:
      - DNT
      - X-CustomHeader
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Authorization
      - Accept
      exposeHeaders:
      - Docker-Content-Digest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
      - name: ui
        image: joxit/docker-registry-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: REGISTRY_URL
          value: "https://registry.homelab"
        - name: SINGLE_REGISTRY
          value: "true"
        - name: DELETE_IMAGES
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: container-registry
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: docker-registry-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: docker-registry-ui
  namespace: container-registry
spec:
  hosts:
  - "registry-ui.homelab"
  gateways:
  - istio-system/main-gateway
  http:
  - match:
    - uri:
        prefix: /oauth2/
    route:
    - destination:
        host: oauth2-proxy.security.svc.cluster.local
        port:
          number: 4180
  - route:
    - destination:
        host: docker-registry-ui
        port:
          number: 80