apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications-namespace.yaml
  - cluster-config.yaml
  - argo-workflows-rbac.yaml
  - workflow-rbac.yaml
  - network-policies-dns.yaml

