apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-patcher
  namespace: applications
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-patcher-binding
  namespace: applications
subjects:
- kind: ServiceAccount
  name: default
  namespace: applications
roleRef:
  kind: Role
  name: workflow-patcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-admin
  namespace: databases
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["podchaos"]
  verbs: ["create", "delete", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-admin-binding
  namespace: databases
subjects:
- kind: ServiceAccount
  name: default
  namespace: applications
roleRef:
  kind: Role
  name: chaos-admin
  apiGroup: rbac.authorization.k8s.io
