apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluence-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 18.5.16
    chart: postgresql
    helm:
      values: |
        image:
          repository: bitnamilegacy/postgresql
          tag: 17.6.0-debian-12-r0
        global:
          postgresql:
            auth:
              database: confluence
              username: confluence
              existingSecret: confluence-db-credentials
        
        primary:
          persistence:
            enabled: true
            storageClass: "openebs-hostpath"
            size: 10Gi
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
