apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://atlassian.github.io/data-center-helm-charts'
    targetRevision: 2.0.12
    chart: confluence
    helm:
      values: |
        confluence:
          service:
            type: ClusterIP
            port: 80
          readinessProbe:
            initialDelaySeconds: 120
          resources:
            jvm:
              maxHeap: "4g"
              minHeap: "2g"
            container:
              requests:
                cpu: "1000m"
                memory: "4Gi"
              limits:
                cpu: "4000m"
                memory: "8Gi"
          persistence:
            size: 20Gi
            storageClassName: "openebs-hostpath"
          
          database:
            type: postgresql
            url: "jdbc:postgresql://confluence-db-postgresql.databases.svc.cluster.local:5432/confluence"
            credentials:
              secretName: confluence-db-credentials
              usernameKey: username
              passwordKey: password
        
        ingress:
          create: true
          host: confluence.homelab
          annotations:
            kubernetes.io/ingress.class: nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: collaboration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
