apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docmost-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 20.6.1
    chart: redis
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          repository: bitnamilegacy/redis
          tag: 7.4.1-debian-12-r2
        architecture: standalone
        auth:
          enabled: true
          password: "abc123"
        master:
          persistence:
            enabled: true
            storageClass: "openebs-hostpath"
            size: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
