apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.21.0
    chart: cni
    helm:
      values: |
        cni:
          enabled: true
          # Katalogi specyficzne dla ścieżek w Talos OS
          cniBinDir: /opt/cni/bin
          cniConfDir: /etc/cni/net.d
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true