apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: 0.6.0
    helm:
      valueFiles:
      - values.yaml # This refers to values in the chart, but we will use the localstack-values.yaml in our GitOps flow usually.
      # In a real setup, you might point to the values file in this repo.
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
