apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      values: |
        loki:
          persistence:
            enabled: true
            storageClassName: "openebs-hostpath"
            size: 10Gi
            
        promtail:
          enabled: true
          # Promtail musi mieć dostęp do logów na węźle, więc wymaga podniesionych uprawnień
          config:
            clients:
              - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true