apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cluster-tls
  namespace: databases
spec:
  secretName: redis-cluster-tls
  privateKey:
    encoding: PKCS8
  usages:
    - server auth
    - client auth
  dnsNames:
    - redis-redis-cluster
    - redis-redis-cluster.databases.svc
    - redis-redis-cluster.databases.svc.cluster.local
    - "*.redis-redis-cluster-headless"
    - "*.redis-redis-cluster-headless.databases.svc"
    - "*.redis-redis-cluster-headless.databases.svc.cluster.local"
  ipAddresses:
    - 10.0.0.161
    - 10.0.0.162
    - 10.0.0.163
    - 10.0.0.164
    - 10.0.0.165
    - 10.0.0.166
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
