apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: titan-auth
  namespace: databases
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: titan-db-role
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-cluster-credentials
  namespace: databases
spec:
  vaultAuthRef: titan-auth
  mount: secret
  type: kv-v2
  path: titan/redis-cluster-credentials
  destination:
    name: redis-cluster-credentials
    create: true
