apiVersion: k8s.keycloak.org/v2beta1
kind: KeycloakRealmImport
metadata:
  name: titan-realm
  namespace: security
spec:
  keycloakCRName: titan-keycloak
  realm:
    id: titan
    realm: titan
    displayName: Titan Payments
    enabled: true
    sslRequired: none
