apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak-auth
  namespace: security
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: titan-app-role
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-db-secret
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/keycloak-db-cluster-app
  destination:
    name: keycloak-db-cluster-app
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-payment-client-secret
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/keycloak-payment-service-client
  destination:
    name: keycloak-payment-service-client
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-admin-credentials
  namespace: security
spec:
  vaultAuthRef: keycloak-auth
  mount: secret
  type: kv-v2
  path: titan/keycloak-admin
  destination:
    name: keycloak-admin-credentials
    create: true
