apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redis/redisinsight:2.60.0
        ports:
        - containerPort: 5540
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: db
          mountPath: /data
      volumes:
      - name: db
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: databases
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5540
  selector:
    app: redisinsight
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight
  namespace: databases
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
spec:
  tls:
    - hosts:
        - redis-insight.homelab
      secretName: redisinsight-tls-secret
  rules:
  - host: redis-insight.homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redisinsight
            port:
              number: 80