apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki.yaml
  - metric-server-app.yaml
  - peryscope.yaml
  - prometheus-stack.yaml
  - temp.yaml

configMapGenerator:
  - name: sample-dashboard
    namespace: monitoring
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/sample-dashboard.json
